[package]
name = "domain"
version.workspace = true
edition.workspace = true

[dependencies]
sqlx.workspace = true
serde.workspace = true
chrono.workspace = true
async-trait.workspace = true
tracing-subscriber.workspace = true

common.workspace = true
